name: Feature Request
description: Suggest an idea for this project
labels: [enhancement]
title: "[Feature] "
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a feature! Please provide as much detail as possible.
  - type: input
    id: summary
    attributes:
      label: Feature Summary
      description: Short summary of the feature
      placeholder: e.g. Add IPv6 support
    validations:
      required: true
  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Why is this feature important?
      placeholder: This would help users who ...
    validations:
      required: true
  - type: textarea
    id: details
    attributes:
      label: Feature Details
      description: Describe the feature in detail
      placeholder: The feature should ...
    validations:
      required: true
